#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --nodes=1
#SBATCH --partition=cpu-long
#SBATCH --job-name=N8-2-b0.25
#SBATCH --mem-per-cpu=4G
#SBATCH --mail-user=bukva@lorentz.leidenuniv.nl
#SBATCH --mail-type=END

module load TensorFlow/2.4.1-fosscuda-2020b

python accuracy.py
